#慧博保全表格数据对照表
保全类型:
  新增: ①新增
  变更: ③变更
  终止: ②终止

家属关系:
  计划四: 子女
  计划十三: 子女
  计划九: 配偶

证件类型:
  中国: 居民身份证
  中国香港: 港澳通行证
  中国台湾: 台湾通行证

保险计划:
  计划一: 0000273086-老员工（社保）
  计划二: 0000273087-新员工（社保）
  计划三: 0000273088-出差新员工（社保）
  计划四: 0000273089-子女
  计划五: 0000273090-实习生计划无社保
  计划六: 0000273091-出差老员工计划
  计划七: 0000273092-出差实习生计划（无社保）
  计划八: 0000273093-新员工计划（无社保）
  计划九: 0000273094-配偶计划
  计划十一: 0000273096-管培生计划（无社保）
  计划十二: 0000273097-无社保外籍老员工计划
  计划十三: 0000273098-老员工子女
  计划十五: 0000273100-高管计划-2（社保）
  计划十四: 0000273099-员工计划-2
  计划十: 0000273095-无社保高管计划
#'0000273086-老员工（社保）', '0000273087-新员工（社保）', '0000273088-出差新员工（社保）', 
#'0000273090-实习生计划无社保', '0000273091-出差老员工计划', '0000273092-出差实习生计划（无社保）', 
#'0000273093-新员工计划（无社保）', '0000273095-无社保高管计划', '0000273096-管培生计划（无社保）', 
#'0000273097-无社保外籍老员工计划', '0000273099-员工计划-2', '0000273100-高管计划-2（社保）'

分支机构:
  慧博: H00065086-慧博云通科技股份有限公司
  元年: 0043216999-北京慧博元年科技有限公司
  慧海青岛分: 0043218340-杭州慧海软件技术有限公司青岛分公司

职业类型:
  员工: 一般职业-机关团体公司-机关内勤(不从事危险工作)-1
  配偶: 一般职业-机关团体公司-机关内勤(不从事危险工作)-1
  子女: 文教机构-教育机构-学生(PB等级以投保人职业代码的WP等级为准)-2
  儿童: 服务业-家政管理-儿童(PB等级以投保人职业代码的WP等级为准)-2

员工表列名:
  保全类型: A
  变更项目: B
  分支机构: C
  员工姓名: D
  证件类型: E
  证件号码: F
  职业类型: L
  保障计划: M
  生效日期: N
  是否医保: O
  国籍: S

家属表列名:
  保全类型: A
  变更项目: B
  分支机构: C
  员工姓名: D
  员工证件类型: E
  员工证件号码: F
  家属姓名: G
  家属证件类型: H
  家属证件号码: I
  职业类型: O
  保障计划: P
  家属关系: Q
  生效日期: R
  是否医保: S
  国籍: W